      SUBROUTINE WOLFE(NDM,M,PMAT,ISTRT,S,NCOR,ICOR,IWORK,LIWRK,WORK,
     *LWRK,R,COEF,PTNR,PMAT1,NPARM,NUMGR,WCOEF,WPT,WDIST,NMAJ,NMIN,
     *JFLAG)
C
      IMPLICIT REAL*8 (A-H,O-Z)
      external dotprd
C
      DIMENSION PMAT(NPARM+1,NUMGR),ICOR(NPARM+1),WCOEF(NUMGR),
     *WPT(NPARM),R(NPARM+1),COEF(NUMGR),PTNR(NPARM+1),
     *PMAT1(NPARM+1,NUMGR),IWORK(LIWRK),WORK(LWRK)
C
      WDIST=SQRT(DOTPRD(NDM,PTNR,PTNR,NPARM))
C
      END
C
      FUNCTION DOTPRD(LGTH,VEC1,VEC2,NPARM)
C
      IMPLICIT REAL*8 (A-H,O-Z)
C
      DIMENSION VEC1(NPARM+1),VEC2(NPARM+1)
C
C THIS SUBPROGRAM COMPUTES THE DOT PRODUCT OF VECTORS VEC1
C AND VEC2 OF LENGTH LGTH.
C VEC1 AND VEC2 DO NOT APPEAR IN FUNCTION ILOC SINCE THEY ARE USED ONLY
C AS INPUT NAMES FOR THIS SUBPROGRAM, AND SO THEY DON'T NEED TO HAVE
C SPACE RESERVED FOR THEM IN THE ARRAY WORK.
      DD=VEC1(1)*VEC2(1)
      IF(LGTH-1)300,300,100
  100 DO 200 J=2,LGTH
        DD=DD+VEC1(J)*VEC2(J)
  200   CONTINUE
  300 DOTPRD=DD
      RETURN
      END
