/* Generated By:JavaCC: Do not edit this line. FormatParserConstants.java */
package org.j_paine.formatter;

public interface FormatParserConstants {

  int EOF = 0;
  int INTEGER = 2;
  int STRING = 3;
  int A_DESC = 4;
  int P_DESC = 5;
  int X_DESC = 6;
  int I_DESC = 7;
  int F_DESC = 8;
  int D_DESC = 9;
  int E_DESC = 10;
  int G_DESC = 11;
  int L_DESC = 12;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "<token of kind 1>",
    "<INTEGER>",
    "<STRING>",
    "<A_DESC>",
    "<P_DESC>",
    "<X_DESC>",
    "<I_DESC>",
    "<F_DESC>",
    "<D_DESC>",
    "<E_DESC>",
    "<G_DESC>",
    "<L_DESC>",
    "\"-\"",
    "\".\"",
    "\"/\"",
    "\"(\"",
    "\")\"",
    "\",\"",
  };

}
