
test7.class: clean
	f2java test7.f
	rm *.class
	javac Test7.java
	javab *.class

test6.class: clean
	f2java test6.f
	rm *.class
	javac Test6.java
	javab *.class

clean:
	/bin/rm -f *.class *.java *.old *.f2j a.out
