/* Generated By:JavaCC: Do not edit this line. NumberParserConstants.java */
package org.j_paine.formatter;

public interface NumberParserConstants {

  int EOF = 0;
  int INTEGER_LITERAL = 1;
  int DECIMAL_LITERAL = 2;
  int LOGICAL_LITERAL = 3;
  int FLOATING_POINT_LITERAL = 4;
  int EXPONENT = 5;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<LOGICAL_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<EXPONENT>",
    "\" \"",
    "\"-\"",
    "\"+\"",
  };

}
