#!/bin/sh

echo "F2J=f2java"
echo "JAVA=java"
echo "JAVAC=javac"
echo "TEMP_OUT=temp.out"
echo ""

for file in *.f; do
  testnum=`echo $file | sed s/FM// | cut -d . -f 1`
  echo "test${testnum}: clean"
  echo "	\$(F2J) FM${testnum}.f"
  echo "	if \[ -e FM${testnum}.DAT \]; then \\"
  echo "	\$(JAVA) Fm${testnum} < FM${testnum}.DAT > \$(TEMP_OUT); \\"
  echo "	else \\"
  echo "	\$(JAVA) Fm${testnum} > \$(TEMP_OUT); \\"
  echo "	fi"
  echo ""
done

echo "clean:"
echo "	/bin/rm -f *.class *.java *.f2j *.old a.out fort.*"
