F2J=f2java
JAVA=java
JAVAC=javac

test001: clean
	$(F2J) FM001.f
	$(JAVA) Fm001

test002: clean
	$(F2J) FM002.f
	$(JAVA) Fm002

test003: clean
	$(F2J) FM003.f
	$(JAVA) Fm003

test004: clean
	$(F2J) FM004.f
	$(JAVA) Fm004

test005: clean
	$(F2J) FM005.f
	$(JAVA) Fm005

test006: clean
	$(F2J) FM006.f
	$(JAVA) Fm006

test007: clean
	$(F2J) FM007.f
	$(JAVA) Fm007

test008: clean
	$(F2J) FM008.f
	$(JAVA) Fm008

test009: clean
	$(F2J) FM009.f
	$(JAVA) Fm009

test010: clean
	$(F2J) FM010.f
	$(JAVA) Fm010

test011: clean
	$(F2J) FM011.f
	$(JAVA) Fm011

test012: clean
	$(F2J) FM012.f
	$(JAVA) Fm012

test013: clean
	$(F2J) FM013.f
	$(JAVA) Fm013

test014: clean
	$(F2J) FM014.f
	$(JAVA) Fm014

test016: clean
	$(F2J) FM016.f
	$(JAVA) Fm016

test017: clean
	$(F2J) FM017.f
	$(JAVA) Fm017

test018: clean
	$(F2J) FM018.f
	$(JAVA) Fm018

test019: clean
	$(F2J) FM019.f
	$(JAVA) Fm019

test020: clean
	$(F2J) FM020.f
	$(JAVA) Fm020

test021: clean
	$(F2J) FM021.f
	$(JAVA) Fm021

test022: clean
	$(F2J) FM022.f
	$(JAVA) Fm022

test023: clean
	$(F2J) FM023.f
	$(JAVA) Fm023

test024: clean
	$(F2J) FM024.f
	$(JAVA) Fm024

test025: clean
	$(F2J) FM025.f
	$(JAVA) Fm025

test026: clean
	$(F2J) FM026.f
	$(JAVA) Fm026

test028: clean
	$(F2J) FM028.f
	$(JAVA) Fm028

test030: clean
	$(F2J) FM030.f
	$(JAVA) Fm030

test031: clean
	$(F2J) FM031.f
	$(JAVA) Fm031

test032: clean
	$(F2J) FM032.f
	$(JAVA) Fm032

test033: clean
	$(F2J) FM033.f
	$(JAVA) Fm033

test034: clean
	$(F2J) FM034.f
	$(JAVA) Fm034

test035: clean
	$(F2J) FM035.f
	$(JAVA) Fm035

test036: clean
	$(F2J) FM036.f
	$(JAVA) Fm036

test037: clean
	$(F2J) FM037.f
	$(JAVA) Fm037

test038: clean
	$(F2J) FM038.f
	$(JAVA) Fm038

test039: clean
	$(F2J) FM039.f
	$(JAVA) Fm039

test040: clean
	$(F2J) FM040.f
	$(JAVA) Fm040

test041: clean
	$(F2J) FM041.f
	$(JAVA) Fm041

test042: clean
	$(F2J) FM042.f
	$(JAVA) Fm042

test043: clean
	$(F2J) FM043.f
	$(JAVA) Fm043

test044: clean
	$(F2J) FM044.f
	$(JAVA) Fm044

test045: clean
	$(F2J) FM045.f
	$(JAVA) Fm045

test050: clean
	$(F2J) FM050.f
	$(JAVA) Fm050

test056: clean
	$(F2J) FM056.f
	$(JAVA) Fm056

test060: clean
	$(F2J) FM060.f
	$(JAVA) Fm060

test061: clean
	$(F2J) FM061.f
	$(JAVA) Fm061

test062: clean
	$(F2J) FM062.f
	$(JAVA) Fm062

test080: clean
	$(F2J) FM080.f
	$(JAVA) Fm080

test097: clean
	$(F2J) FM097.f
	$(JAVA) Fm097

test098: clean
	$(F2J) FM098.f
	$(JAVA) Fm098

test099: clean
	$(F2J) FM099.f
	$(JAVA) Fm099

test100: clean
	$(F2J) FM100.f
	$(JAVA) Fm100

test101: clean
	$(F2J) FM101.f
	$(JAVA) Fm101

test102: clean
	$(F2J) FM102.f
	$(JAVA) Fm102

test103: clean
	$(F2J) FM103.f
	$(JAVA) Fm103

test104: clean
	$(F2J) FM104.f
	$(JAVA) Fm104

test105: clean
	$(F2J) FM105.f
	$(JAVA) Fm105

test106: clean
	$(F2J) FM106.f
	$(JAVA) Fm106

test107: clean
	$(F2J) FM107.f
	$(JAVA) Fm107

test108: clean
	$(F2J) FM108.f
	$(JAVA) Fm108

test109: clean
	$(F2J) FM109.f
	$(JAVA) Fm109

test110: clean
	$(F2J) FM110.f
	$(JAVA) Fm110

test111: clean
	$(F2J) FM111.f
	$(JAVA) Fm111

test200: clean
	$(F2J) FM200.f
	$(JAVA) Fm200

test201: clean
	$(F2J) FM201.f
	$(JAVA) Fm201

test202: clean
	$(F2J) FM202.f
	$(JAVA) Fm202

test203: clean
	$(F2J) FM203.f
	$(JAVA) Fm203

test204: clean
	$(F2J) FM204.f
	$(JAVA) Fm204

test205: clean
	$(F2J) FM205.f
	$(JAVA) Fm205

test251: clean
	$(F2J) FM251.f
	$(JAVA) Fm251

test252: clean
	$(F2J) FM252.f
	$(JAVA) Fm252

test253: clean
	$(F2J) FM253.f
	$(JAVA) Fm253

test254: clean
	$(F2J) FM254.f
	$(JAVA) Fm254

test255: clean
	$(F2J) FM255.f
	$(JAVA) Fm255

test256: clean
	$(F2J) FM256.f
	$(JAVA) Fm256

test257: clean
	$(F2J) FM257.f
	$(JAVA) Fm257

test258: clean
	$(F2J) FM258.f
	$(JAVA) Fm258

test259: clean
	$(F2J) FM259.f
	$(JAVA) Fm259

test260: clean
	$(F2J) FM260.f
	$(JAVA) Fm260

test261: clean
	$(F2J) FM261.f
	$(JAVA) Fm261

test300: clean
	$(F2J) FM300.f
	$(JAVA) Fm300

test301: clean
	$(F2J) FM301.f
	$(JAVA) Fm301

test302: clean
	$(F2J) FM302.f
	$(JAVA) Fm302

test306: clean
	$(F2J) FM306.f
	$(JAVA) Fm306

test307: clean
	$(F2J) FM307.f
	$(JAVA) Fm307

test308: clean
	$(F2J) FM308.f
	$(JAVA) Fm308

test311: clean
	$(F2J) FM311.f
	$(JAVA) Fm311

test317: clean
	$(F2J) FM317.f
	$(JAVA) Fm317

test328: clean
	$(F2J) FM328.f
	$(JAVA) Fm328

test351: clean
	$(F2J) FM351.f
	$(JAVA) Fm351

test352: clean
	$(F2J) FM352.f
	$(JAVA) Fm352

test353: clean
	$(F2J) FM353.f
	$(JAVA) Fm353

test354: clean
	$(F2J) FM354.f
	$(JAVA) Fm354

test355: clean
	$(F2J) FM355.f
	$(JAVA) Fm355

test356: clean
	$(F2J) FM356.f
	$(JAVA) Fm356

test357: clean
	$(F2J) FM357.f
	$(JAVA) Fm357

test359: clean
	$(F2J) FM359.f
	$(JAVA) Fm359

test360: clean
	$(F2J) FM360.f
	$(JAVA) Fm360

test361: clean
	$(F2J) FM361.f
	$(JAVA) Fm361

test362: clean
	$(F2J) FM362.f
	$(JAVA) Fm362

test363: clean
	$(F2J) FM363.f
	$(JAVA) Fm363

test364: clean
	$(F2J) FM364.f
	$(JAVA) Fm364

test368: clean
	$(F2J) FM368.f
	$(JAVA) Fm368

test369: clean
	$(F2J) FM369.f
	$(JAVA) Fm369

test370: clean
	$(F2J) FM370.f
	$(JAVA) Fm370

test371: clean
	$(F2J) FM371.f
	$(JAVA) Fm371

test372: clean
	$(F2J) FM372.f
	$(JAVA) Fm372

test373: clean
	$(F2J) FM373.f
	$(JAVA) Fm373

test374: clean
	$(F2J) FM374.f
	$(JAVA) Fm374

test375: clean
	$(F2J) FM375.f
	$(JAVA) Fm375

test376: clean
	$(F2J) FM376.f
	$(JAVA) Fm376

test377: clean
	$(F2J) FM377.f
	$(JAVA) Fm377

test378: clean
	$(F2J) FM378.f
	$(JAVA) Fm378

test379: clean
	$(F2J) FM379.f
	$(JAVA) Fm379

test401: clean
	$(F2J) FM401.f
	$(JAVA) Fm401

test402: clean
	$(F2J) FM402.f
	$(JAVA) Fm402

test403: clean
	$(F2J) FM403.f
	$(JAVA) Fm403

test404: clean
	$(F2J) FM404.f
	$(JAVA) Fm404

test405: clean
	$(F2J) FM405.f
	$(JAVA) Fm405

test406: clean
	$(F2J) FM406.f
	$(JAVA) Fm406

test407: clean
	$(F2J) FM407.f
	$(JAVA) Fm407

test411: clean
	$(F2J) FM411.f
	$(JAVA) Fm411

test413: clean
	$(F2J) FM413.f
	$(JAVA) Fm413

test500: clean
	$(F2J) FM500.f
	$(JAVA) Fm500

test503: clean
	$(F2J) FM503.f
	$(JAVA) Fm503

test506: clean
	$(F2J) FM506.f
	$(JAVA) Fm506

test509: clean
	$(F2J) FM509.f
	$(JAVA) Fm509

test514: clean
	$(F2J) FM514.f
	$(JAVA) Fm514

test517: clean
	$(F2J) FM517.f
	$(JAVA) Fm517

test520: clean
	$(F2J) FM520.f
	$(JAVA) Fm520

test700: clean
	$(F2J) FM700.f
	$(JAVA) Fm700

test701: clean
	$(F2J) FM701.f
	$(JAVA) Fm701

test710: clean
	$(F2J) FM710.f
	$(JAVA) Fm710

test711: clean
	$(F2J) FM711.f
	$(JAVA) Fm711

test715: clean
	$(F2J) FM715.f
	$(JAVA) Fm715

test718: clean
	$(F2J) FM718.f
	$(JAVA) Fm718

test719: clean
	$(F2J) FM719.f
	$(JAVA) Fm719

test722: clean
	$(F2J) FM722.f
	$(JAVA) Fm722

test800: clean
	$(F2J) FM800.f
	$(JAVA) Fm800

test801: clean
	$(F2J) FM801.f
	$(JAVA) Fm801

test802: clean
	$(F2J) FM802.f
	$(JAVA) Fm802

test803: clean
	$(F2J) FM803.f
	$(JAVA) Fm803

test804: clean
	$(F2J) FM804.f
	$(JAVA) Fm804

test805: clean
	$(F2J) FM805.f
	$(JAVA) Fm805

test806: clean
	$(F2J) FM806.f
	$(JAVA) Fm806

test807: clean
	$(F2J) FM807.f
	$(JAVA) Fm807

test808: clean
	$(F2J) FM808.f
	$(JAVA) Fm808

test809: clean
	$(F2J) FM809.f
	$(JAVA) Fm809

test810: clean
	$(F2J) FM810.f
	$(JAVA) Fm810

test811: clean
	$(F2J) FM811.f
	$(JAVA) Fm811

test812: clean
	$(F2J) FM812.f
	$(JAVA) Fm812

test813: clean
	$(F2J) FM813.f
	$(JAVA) Fm813

test814: clean
	$(F2J) FM814.f
	$(JAVA) Fm814

test815: clean
	$(F2J) FM815.f
	$(JAVA) Fm815

test816: clean
	$(F2J) FM816.f
	$(JAVA) Fm816

test817: clean
	$(F2J) FM817.f
	$(JAVA) Fm817

test818: clean
	$(F2J) FM818.f
	$(JAVA) Fm818

test819: clean
	$(F2J) FM819.f
	$(JAVA) Fm819

test820: clean
	$(F2J) FM820.f
	$(JAVA) Fm820

test821: clean
	$(F2J) FM821.f
	$(JAVA) Fm821

test822: clean
	$(F2J) FM822.f
	$(JAVA) Fm822

test823: clean
	$(F2J) FM823.f
	$(JAVA) Fm823

test824: clean
	$(F2J) FM824.f
	$(JAVA) Fm824

test825: clean
	$(F2J) FM825.f
	$(JAVA) Fm825

test826: clean
	$(F2J) FM826.f
	$(JAVA) Fm826

test827: clean
	$(F2J) FM827.f
	$(JAVA) Fm827

test828: clean
	$(F2J) FM828.f
	$(JAVA) Fm828

test829: clean
	$(F2J) FM829.f
	$(JAVA) Fm829

test830: clean
	$(F2J) FM830.f
	$(JAVA) Fm830

test831: clean
	$(F2J) FM831.f
	$(JAVA) Fm831

test832: clean
	$(F2J) FM832.f
	$(JAVA) Fm832

test833: clean
	$(F2J) FM833.f
	$(JAVA) Fm833

test834: clean
	$(F2J) FM834.f
	$(JAVA) Fm834

test900: clean
	$(F2J) FM900.f
	$(JAVA) Fm900

test901: clean
	$(F2J) FM901.f
	$(JAVA) Fm901

test903: clean
	$(F2J) FM903.f
	$(JAVA) Fm903

test905: clean
	$(F2J) FM905.f
	$(JAVA) Fm905

test906: clean
	$(F2J) FM906.f
	$(JAVA) Fm906

test907: clean
	$(F2J) FM907.f
	$(JAVA) Fm907

test908: clean
	$(F2J) FM908.f
	$(JAVA) Fm908

test909: clean
	$(F2J) FM909.f
	$(JAVA) Fm909

test910: clean
	$(F2J) FM910.f
	$(JAVA) Fm910

test912: clean
	$(F2J) FM912.f
	$(JAVA) Fm912

test914: clean
	$(F2J) FM914.f
	$(JAVA) Fm914

test915: clean
	$(F2J) FM915.f
	$(JAVA) Fm915

test916: clean
	$(F2J) FM916.f
	$(JAVA) Fm916

test917: clean
	$(F2J) FM917.f
	$(JAVA) Fm917

test919: clean
	$(F2J) FM919.f
	$(JAVA) Fm919

test920: clean
	$(F2J) FM920.f
	$(JAVA) Fm920

test921: clean
	$(F2J) FM921.f
	$(JAVA) Fm921

test922: clean
	$(F2J) FM922.f
	$(JAVA) Fm922

test923: clean
	$(F2J) FM923.f
	$(JAVA) Fm923

clean:
	/bin/rm -f *.class *.java *.f2j *.old a.out fort.*
